-- Flatout ERP V1 production schema
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','sales','operations');
create type public.item_type as enum ('Product','Labor/Service','Shipping','Miscellaneous','Discount');
create type public.purchase_status as enum ('Need to Order','Ordered','Backordered','Shipped','Received','N/A');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,email text,role public.user_role not null default 'sales',active boolean not null default true,created_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(),name text not null,company text,email text,phone text,billing_address text,shipping_address text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),sku text unique,name text not null,vendor text,category text,sell_price numeric(12,2) not null default 0,cost numeric(12,2),image_ref text,active boolean not null default true,source_key text,last_synced_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),order_number text unique not null,customer_id uuid not null references public.customers(id),status text not null default 'Draft',payment_status text not null default 'Not Invoiced',tax_rate numeric(6,4) not null default 0,order_notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id),item_type public.item_type not null default 'Product',description text not null,sku text,vendor text,qty numeric(10,2) not null default 1,sell_price numeric(12,2) not null default 0,cost numeric(12,2),purchasing_status public.purchase_status not null default 'Need to Order',tracking text,notes text,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.item_notes(id uuid primary key default gen_random_uuid(),order_item_id uuid not null references public.order_items(id) on delete cascade,note text not null,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.price_sync_runs(id uuid primary key default gen_random_uuid(),source text not null default 'Google Sheets Price Guide',status text not null default 'preview',new_products integer not null default 0,changed_products integer not null default 0,missing_products integer not null default 0,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),applied_at timestamptz);
-- Create a profile whenever a Supabase Auth user is created.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
-- Security
alter table public.profiles enable row level security;alter table public.customers enable row level security;alter table public.products enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.item_notes enable row level security;alter table public.price_sync_runs enable row level security;
create or replace function public.is_active_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active); $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role='admin'); $$;
create policy "staff read profiles" on public.profiles for select using(public.is_active_staff());create policy "admin update profiles" on public.profiles for update using(public.is_admin()) with check(public.is_admin());
create policy "staff customers" on public.customers for all using(public.is_active_staff()) with check(public.is_active_staff());create policy "staff products" on public.products for all using(public.is_active_staff()) with check(public.is_active_staff());create policy "staff orders" on public.orders for all using(public.is_active_staff()) with check(public.is_active_staff());create policy "staff order items" on public.order_items for all using(public.is_active_staff()) with check(public.is_active_staff());create policy "staff notes" on public.item_notes for all using(public.is_active_staff()) with check(public.is_active_staff());create policy "staff sync runs" on public.price_sync_runs for select using(public.is_active_staff());create policy "admin sync runs" on public.price_sync_runs for insert with check(public.is_admin());create policy "admin sync update" on public.price_sync_runs for update using(public.is_admin()) with check(public.is_admin());
