'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase-browser';

type Row=Record<string,any>;
type Tab='Sales Accounting Overview'|'Payments'|'Outstanding Balances'|'Expenses'|'Vendor Bills'|'Financial Reports';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const num=(n:any)=>Number(n||0);
const day=()=>new Date().toLocaleDateString('en-CA');
const categories=['Advertising','Bank Fees','Equipment','Insurance','Office','Professional Services','Rent','Repairs','Shipping','Software','Supplies','Travel','Utilities','Other'];

export default function AccountingWorkspace({tab,openOrder}:{tab:Tab;openOrder:(id:string)=>void}){
 const db=useMemo(()=>supabase(),[]);
 const [orders,setOrders]=useState<Row[]>([]),[expenses,setExpenses]=useState<Row[]>([]),[bills,setBills]=useState<Row[]>([]),[pos,setPos]=useState<Row[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState('');
 const [expenseForm,setExpenseForm]=useState({expense_date:day(),vendor:'',description:'',category:'Software',amount:'',payment_method:'',reference:'',notes:''});
 const [billForm,setBillForm]=useState({bill_number:'',vendor:'',purchase_order_id:'',bill_date:day(),due_date:'',subtotal:'',tax_amount:'0',shipping_amount:'0',notes:''});
 const [billPayment,setBillPayment]=useState('');
 const fetchAll=useCallback(async(table:string,select:string,sort:string)=>{
  const out:Row[]=[];for(let from=0;from<100000;from+=500){const {data,error}=await db.from(table).select(select).order(sort,{ascending:false}).range(from,from+499);if(error)throw new Error(`${table}: ${error.message}`);out.push(...(data||[]));if((data||[]).length<500)return out;}throw new Error(`${table}: over 100,000 records; reporting requires server-side pagination`);
 },[db]);
 const refresh=useCallback(async()=>{
  setBusy(true);setError('');try{
   const [o,e,b,p]=await Promise.all([
    fetchAll('orders','id,order_number,status,payment_status,tax_rate,tax_exempt,shipping_amount,created_at,customers(name),order_items(qty,sell_price,cost),payments(id,amount,payment_method,reference,paid_at),payment_adjustments(id,payment_id,adjustment_type,amount,created_at)','created_at'),
    fetchAll('expenses','*','expense_date'),
    fetchAll('vendor_bills','*,vendor_bill_payments(*)','bill_date'),
    fetchAll('purchase_orders','id,po_number,vendor','created_at')
   ]);setOrders(o);setExpenses(e);setBills(b);setPos(p);
  }catch(e:any){setError(e.message||'Unable to load accounting records.');}finally{setBusy(false);}
 },[fetchAll]);
 useEffect(()=>{void refresh();},[refresh]);
 const sales=useMemo(()=>orders.filter(o=>o.status!=='Draft').map(o=>{
  const subtotal=(o.order_items||[]).reduce((s:number,i:Row)=>s+num(i.qty)*num(i.sell_price),0);
  const cost=(o.order_items||[]).reduce((s:number,i:Row)=>s+num(i.qty)*num(i.cost),0);
  const tax=o.tax_exempt?0:subtotal*num(o.tax_rate)/100;
  const total=subtotal+tax+num(o.shipping_amount);
  const gross=(o.payments||[]).reduce((s:number,p:Row)=>s+num(p.amount),0);
  const adjustments=(o.payment_adjustments||[]).reduce((s:number,a:Row)=>s+num(a.amount),0);
  const paid=gross-adjustments;
  return {...o,subtotal,cost,tax,total,paid,balance:Math.max(0,total-paid)};
 }),[orders]);
 const sums=useMemo(()=>({orderValue:sales.reduce((a,o)=>a+o.total,0),paid:sales.reduce((a,o)=>a+o.paid,0),balance:sales.reduce((a,o)=>a+o.balance,0),salesSubtotal:sales.reduce((a,o)=>a+o.subtotal,0),estimatedCost:sales.reduce((a,o)=>a+o.cost,0),expenses:expenses.filter(e=>e.status==='Recorded').reduce((a,e)=>a+num(e.amount),0),billTotal:bills.filter(b=>b.status==='Open').reduce((a,b)=>a+num(b.subtotal)+num(b.tax_amount)+num(b.shipping_amount),0),billPaid:bills.filter(b=>b.status==='Open').reduce((a,b)=>a+(b.vendor_bill_payments||[]).reduce((x:number,p:Row)=>x+num(p.amount),0),0)}),[sales,expenses,bills]);
 const filteredSales=sales.filter(o=>[o.order_number,o.customers?.name].some(x=>String(x||'').toLowerCase().includes(search.toLowerCase())));
 const filteredExpenses=expenses.filter(e=>[e.vendor,e.description,e.category].some(x=>String(x||'').toLowerCase().includes(search.toLowerCase())));
 const filteredBills=bills.filter(b=>[b.vendor,b.bill_number].some(x=>String(x||'').toLowerCase().includes(search.toLowerCase())));
 const saveExpense=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(num(expenseForm.amount)<=0){setError('Expense amount must be positive.');return;}setBusy(true);const {error}=await db.from('expenses').insert({...expenseForm,amount:num(expenseForm.amount),payment_method:expenseForm.payment_method||null,reference:expenseForm.reference||null});setBusy(false);if(error){setError(error.message);return;}setNotice('Expense recorded.');setExpenseForm({expense_date:day(),vendor:'',description:'',category:'Software',amount:'',payment_method:'',reference:'',notes:''});await refresh();};
 const voidExpense=async(e:Row)=>{if(!confirm(`Void expense ${money(num(e.amount))} from ${e.vendor}?`))return;const {error}=await db.from('expenses').update({status:'Voided'}).eq('id',e.id);if(error){setError(error.message);return;}setNotice('Expense voided.');await refresh();};
 const saveBill=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(num(billForm.subtotal)<0||num(billForm.tax_amount)<0||num(billForm.shipping_amount)<0){setError('Bill amounts cannot be negative.');return;}setBusy(true);const {error}=await db.from('vendor_bills').insert({...billForm,purchase_order_id:billForm.purchase_order_id||null,due_date:billForm.due_date||null,subtotal:num(billForm.subtotal),tax_amount:num(billForm.tax_amount),shipping_amount:num(billForm.shipping_amount)});setBusy(false);if(error){setError(error.message);return;}setNotice('Vendor bill recorded.');setBillForm({bill_number:'',vendor:'',purchase_order_id:'',bill_date:day(),due_date:'',subtotal:'',tax_amount:'0',shipping_amount:'0',notes:''});await refresh();};
 const payBill=async(b:Row)=>{const outstanding=num(b.subtotal)+num(b.tax_amount)+num(b.shipping_amount)-(b.vendor_bill_payments||[]).reduce((a:number,p:Row)=>a+num(p.amount),0);const input=prompt(`Record a payment for ${b.vendor} (remaining ${money(outstanding)}).\nThis records an external payment only; no money is sent.`,outstanding.toFixed(2));if(input===null)return;const amount=Number(input);if(!Number.isFinite(amount)||amount<=0||amount>outstanding+.005){setError('Enter a positive payment no greater than the outstanding balance.');return;}const reference=prompt('Payment reference (optional):','');if(reference===null)return;const {error}=await db.from('vendor_bill_payments').insert({vendor_bill_id:b.id,amount,reference:reference||null});if(error){setError(error.message);return;}setNotice('Vendor payment recorded in ERP (not processed).');await refresh();};
 const voidBill=async(b:Row)=>{if((b.vendor_bill_payments||[]).length){setError('Cannot void a bill with recorded payments. Reconcile those payments first.');return;}if(!confirm(`Void bill ${b.bill_number}?`))return;const {error}=await db.from('vendor_bills').update({status:'Void'}).eq('id',b.id);if(error){setError(error.message);return;}setNotice('Vendor bill voided.');await refresh();};
 const field=(label:string,value:string,onChange:(v:string)=>void,type='text',required=false)=><label className="field" style={{minWidth:160,flex:'1 1 180px'}}><span>{label}</span><input type={type} required={required} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} value={value} onChange={e=>onChange(e.target.value)}/></label>;
 const metric=(name:string,value:number)=><div className="card"><div className="muted">{name}</div><div className="value">{money(value)}</div></div>;
 const table=(headers:string[],rows:React.ReactNode[],empty:string)=><div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length} className="muted">{empty}</td></tr>}</tbody></table></div>;
 return <section className="panel" style={{marginTop:16}}><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h2>{tab}</h2><p className="muted">E-commerce and rig builds only · Square session sales and payroll excluded</p></div><button className="btn secondary" onClick={()=>void refresh()} disabled={busy}>{busy?'Loading…':'Refresh'}</button></div>
 {error&&<p role="alert" style={{color:'#ff8b8b'}}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 {(tab==='Sales Accounting Overview'||tab==='Financial Reports')&&<><div className="cards">{metric('Confirmed order value',sums.orderValue)}{metric('Net payments recorded',sums.paid)}{metric('Customer balances due',sums.balance)}{metric('Estimated product gross profit',sums.salesSubtotal-sums.estimatedCost)}{metric('Recorded operating expenses',sums.expenses)}{metric('Vendor bills outstanding',Math.max(0,sums.billTotal-sums.billPaid))}</div><p className="muted">Operational estimates, not a posted general ledger or tax-ready financial statements. Sales include order tax and shipping; estimated product gross profit excludes both. Order costs are estimates, not verified cost of goods sold. Expenses and vendor bills are separate records; avoid entering the same cost twice. No automated journal posting or bank reconciliation is enabled.</p></>}
 {tab==='Payments'&&<><input placeholder="Search order or customer" value={search} onChange={e=>setSearch(e.target.value)}/>{table(['Order','Customer','Date','Type','Method','Reference','Amount'],filteredSales.flatMap(o=>[...(o.payments||[]).map((p:Row)=><tr key={'p'+p.id}><td><button className="btn secondary" onClick={()=>openOrder(o.id)}>{o.order_number}</button></td><td>{o.customers?.name||'—'}</td><td>{String(p.paid_at||'').slice(0,10)}</td><td>Payment</td><td>{p.payment_method||'—'}</td><td>{p.reference||'—'}</td><td>{money(num(p.amount))}</td></tr>),...(o.payment_adjustments||[]).map((a:Row)=><tr key={'a'+a.id}><td><button className="btn secondary" onClick={()=>openOrder(o.id)}>{o.order_number}</button></td><td>{o.customers?.name||'—'}</td><td>{String(a.created_at||'').slice(0,10)}</td><td>{a.adjustment_type}</td><td>—</td><td>—</td><td>-{money(num(a.amount))}</td></tr>)]),'No payments or adjustments recorded.')}</>}
 {tab==='Outstanding Balances'&&<><input placeholder="Search order or customer" value={search} onChange={e=>setSearch(e.target.value)}/>{table(['Order','Customer','Order date','Order total','Net paid','Balance','Action'],filteredSales.filter(o=>o.balance>.005).map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.customers?.name||'—'}</td><td>{String(o.created_at||'').slice(0,10)}</td><td>{money(o.total)}</td><td>{money(o.paid)}</td><td>{money(o.balance)}</td><td><button className="btn secondary" onClick={()=>openOrder(o.id)}>Open invoice</button></td></tr>),'No outstanding customer balances.')}</>}
 {tab==='Expenses'&&<><h3>Record expense</h3><form onSubmit={saveExpense}><div className="row" style={{flexWrap:'wrap'}}>{field('Date',expenseForm.expense_date,v=>setExpenseForm(x=>({...x,expense_date:v})),'date',true)}{field('Vendor',expenseForm.vendor,v=>setExpenseForm(x=>({...x,vendor:v})),'text',true)}{field('Description',expenseForm.description,v=>setExpenseForm(x=>({...x,description:v})),'text',true)}<label className="field">Category<select value={expenseForm.category} onChange={e=>setExpenseForm(x=>({...x,category:e.target.value}))}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>{field('Amount ($)',expenseForm.amount,v=>setExpenseForm(x=>({...x,amount:v})),'number',true)}{field('Payment method',expenseForm.payment_method,v=>setExpenseForm(x=>({...x,payment_method:v})))}{field('Reference',expenseForm.reference,v=>setExpenseForm(x=>({...x,reference:v})))}</div><button className="btn" disabled={busy} type="submit">Record expense</button></form><h3>Expense history</h3><input placeholder="Search expenses" value={search} onChange={e=>setSearch(e.target.value)}/>{table(['Date','Vendor','Description','Category','Amount','Status','Action'],filteredExpenses.map(e=><tr key={e.id}><td>{e.expense_date}</td><td>{e.vendor}</td><td>{e.description}</td><td>{e.category}</td><td>{money(num(e.amount))}</td><td>{e.status}</td><td>{e.status==='Recorded'&&<button className="btn secondary" onClick={()=>void voidExpense(e)}>Void</button>}</td></tr>),'No expenses recorded.')}</>}
 {tab==='Vendor Bills'&&<><h3>Record vendor bill</h3><form onSubmit={saveBill}><div className="row" style={{flexWrap:'wrap'}}>{field('Bill number',billForm.bill_number,v=>setBillForm(x=>({...x,bill_number:v})),'text',true)}{field('Vendor',billForm.vendor,v=>setBillForm(x=>({...x,vendor:v})),'text',true)}<label className="field">Purchase order (optional)<select value={billForm.purchase_order_id} onChange={e=>{const id=e.target.value;const po=pos.find(p=>p.id===id);setBillForm(x=>({...x,purchase_order_id:id,vendor:po?.vendor||x.vendor}));}}><option value="">Not linked</option>{pos.map(p=><option key={p.id} value={p.id}>{p.po_number} · {p.vendor}</option>)}</select></label>{field('Bill date',billForm.bill_date,v=>setBillForm(x=>({...x,bill_date:v})),'date',true)}{field('Due date',billForm.due_date,v=>setBillForm(x=>({...x,due_date:v})),'date')}{field('Subtotal ($)',billForm.subtotal,v=>setBillForm(x=>({...x,subtotal:v})),'number',true)}{field('Tax ($)',billForm.tax_amount,v=>setBillForm(x=>({...x,tax_amount:v})),'number')}{field('Shipping ($)',billForm.shipping_amount,v=>setBillForm(x=>({...x,shipping_amount:v})),'number')}</div><button className="btn" type="submit" disabled={busy}>Record bill</button></form><h3>Vendor bills</h3><input placeholder="Search vendor or bill number" value={search} onChange={e=>setSearch(e.target.value)}/>{table(['Bill','Vendor','Due','Total','Paid','Remaining','Status','Action'],filteredBills.map(b=>{const total=num(b.subtotal)+num(b.tax_amount)+num(b.shipping_amount),paid=(b.vendor_bill_payments||[]).reduce((a:number,p:Row)=>a+num(p.amount),0);return <tr key={b.id}><td>{b.bill_number}</td><td>{b.vendor}</td><td>{b.due_date||'—'}</td><td>{money(total)}</td><td>{money(paid)}</td><td>{money(Math.max(0,total-paid))}</td><td>{b.status}</td><td>{b.status==='Open'&&<div className="row">{total-paid>.005&&<button className="btn secondary" onClick={()=>void payBill(b)}>Record payment</button>}{paid===0&&<button className="btn secondary" onClick={()=>void voidBill(b)}>Void</button>}</div>}</td></tr>;}),'No vendor bills recorded.')}</>}
 {tab==='Financial Reports'&&<><h3>Operational financial summary (all time)</h3>{table(['Metric','Amount'],[['Sales subtotal (excluding tax and shipping)',sums.salesSubtotal],['Estimated item costs',sums.estimatedCost],['Estimated product gross profit',sums.salesSubtotal-sums.estimatedCost],['Recorded operating expenses',sums.expenses],['Illustrative margin after expenses',sums.salesSubtotal-sums.estimatedCost-sums.expenses],['Open vendor bills',sums.billTotal],['Vendor bill payments',sums.billPaid]].map(([name,value])=><tr key={String(name)}><td>{name}</td><td>{money(Number(value))}</td></tr>),'No data') }<p className="muted">Illustrative margin is not net income. Vendor bills may overlap order item costs or recorded expenses and are not subtracted again. Reporting periods, inventory recognition, tax liability, and posted double-entry accounting will require a later reconciliation phase.</p></>}
 </section>;
}
